.github/workflows/lint-golang.yaml, .golangci.yaml, Makefile, pkg/utils/utils.go, plugins/veth/utils.go
Signed-off-by: weizhou.lan@daocloud.io <weizhou.lan@daocloud.io>
=> golang lint

pkg/utils/utils.go, plugins/router/router.go, plugins/veth/utils.go, plugins/veth/veth.go
set sysctl parameters(disable_ipv6) to 0
=> set sysctl parameters(disable_ipv6) to 0

pkg/utils/utils.go, plugins/router/router.go
=> fix config nil pointer

pkg/utils/utils.go, plugins/veth/utils.go, plugins/veth/veth.go
Signed-off-by: weizhoublue <weizhou.lan@daocloud.io>
=> veth: support second interface

images/Dockerfile.amd64, images/Dockerfile.arm64, images/entrypoint.sh
Signed-off-by: weizhoublue <weizhou.lan@daocloud.io>
=> install bin

charts/meta-plugins/Chart.yaml
=> update chart tag to v0.1.3

pkg/types/types.go, pkg/utils/utils.go, plugins/router/router.go, plugins/veth/utils.go, plugins/veth/veth.go
Signed-off-by: weizhou.lan@daocloud.io <weizhou.lan@daocloud.io>
1 support ipv4-only  ipv6-only  dual-stack
2 router cni conf   changed
{
hijack_overlay_reponse :  true/false       ---> remove delDefaultRoute4 and  delDefaultRoute4
overlay_interface         --> remove defaultOverlayInterface ,  统一下滑写法，而不是 有的是驼峰，有的是下滑
}
3 more logs
=> router plugin

charts/meta-plugins/Chart.yaml
=> tag chart v0.1.4

pkg/utils/utils.go, plugins/router/router.go, plugins/veth/veth.go
Signed-off-by: weizhou.lan@daocloud.io <weizhou.lan@daocloud.io>
=> router: set ipv6 default route

README.md, charts/meta-plugins/Chart.yaml
=> update tag to v0.1.5

.github/workflows/image-build.yaml, .github/workflows/release.yaml, charts/meta-plugins/Chart.yaml, charts/meta-plugins/templates/daemonSet.yaml, pkg/utils/utils.go, plugins/router/router.go
=> fix failed to set rp_filter

.github/workflows/image-build.yaml, pkg/types/types.go, pkg/utils/utils.go, plugins/router/router.go, plugins/veth/veth.go
=> adjust the struct of the routes

pkg/logging/log.go, pkg/utils/utils.go, plugins/router/router.go, plugins/veth/utils.go, plugins/veth/veth.go
fix https://github.com/spidernet-io/cni-plugins/issues/37
ipv6 arp解析不成功，只有req无response, 手动在pod内部插入去往主机IP的邻居表、在主机上添加去往 pod underlay网卡的邻居表得以解决(only for ipv6)
=> fix the issue of ipv6 communication failure between pods and host

.github/workflows/image-build.yaml, .github/workflows/lint-golang.yaml, Makefile, Makefile.defs
Signed-off-by: weizhou.lan@daocloud.io <weizhou.lan@daocloud.io>
=> trivy scan

pkg/utils/utils.go
fix https://github.com/spidernet-io/cni-plugins/issues/47
=> ignore error when del rule not exist

.github/workflows/e2e-init.yaml, .github/workflows/e2e-test.yaml, .github/workflows/image-build.yaml, .github/workflows/release.yaml, Makefile, Makefile.defs, README.md, test/Makefile, test/Makefile.defs, test/README.md, test/e2e/README.md, test/e2e/common/const.go, test/scripts/install/01-default-cni.sh, test/scripts/install/02-multus-underlay.sh, test/scripts/install/03-spiderpool.sh, test/scripts/install/04-cni-plugins.sh, test/scripts/kind.sh
=> add github action

.github/workflows/e2e-init.yaml, Makefile, Makefile.defs, charts/meta-plugins/Chart.yaml, charts/meta-plugins/README.md, test/Makefile
=> fix typo & bump to v0.1.8

plugins/router/router.go, test/e2e/macvlan-standalone-one/macvlan_standalone_one_suite_test.go
enable disable_ipv6 in advance
=> enable disable_ipv6 in advance

.github/workflows/ci-bot.yaml, .github/workflows/image-build.yaml, .github/workflows/lint-golang.yaml, .github/workflows/pr-label-check.yaml, .github/workflows/release.yaml, .github/workflows/status.yaml, Makefile, README.md, codecov.yml, docs/Release.md, hack/codeCoverage.sh, hack/todocover.sh, plugins/router/router_test.go, plugins/veth/veth_test.go
add release-note & add badge & add github action
=> add release-note & add badge & add github action

pkg/config/config.go, pkg/config/config_test.go, plugins/router/router.go, plugins/veth/veth.go
opt validate overlaySubnet and overlaySubnet, and add unit tests
=> opt validate overlaySubnet and overlaySubnet, and add unit tests

.github/PULL_REQUEST_TEMPLATE.md, .github/workflows/e2e-init.yaml, .github/workflows/e2e-test.yaml
Fixd https://github.com/spidernet-io/cni-plugins/issues/90
=> support ipv4-only and ipv6-only

.github/workflows/ci-bot.yaml, .github/workflows/e2e-init.yaml, .github/workflows/e2e-test.yaml, .github/workflows/image-build.yaml, .github/workflows/lint-golang.yaml
/kind bug
create an issue when night ci failed
Fixes https://github.com/spidernet-io/cni-plugins/issues/95
```docs
```
=> create an issue when night ci failed

.github/workflows/e2e-test.yaml, .github/workflows/lint-golang.yaml, pkg/utils/utils.go, pkg/utils/utils_suite_test.go, pkg/utils/utils_test.go
/kind feature
unit-test
Fixes #
=> unit-test1

.github/PULL_REQUEST_TEMPLATE.md, .github/workflows/image-build.yaml, pkg/utils/utils_test.go, plugins/router/router.go
fix failed to get defaultOverlayIP
Fixes #
=> fix failed to get defaultOverlayIP

.github/workflows/e2e-init.yaml, .github/workflows/e2e-test.yaml
create an issue doesn't works
Fixes #
=> create an issue

test/e2e/macvlan-overlay-one/macvlan_overlay_one_suite_test.go, test/e2e/macvlan-overlay-one/macvlan_overlay_one_test.go, test/e2e/macvlan-overlay-two/macvlan_overlay_two_suite_test.go, test/e2e/macvlan-overlay-two/macvlan_overlay_two_test.go, test/e2e/macvlan-standalone-one/macvlan_standalone_one_test.go, test/e2e/macvlan-standalone-two/macvlan_standalone_two_suite_test.go, test/e2e/macvlan-standalone-two/macvlan_standalone_two_test.go
Signed-off-by: ji.li@daocloud.io ji.li@daocloud.io
=> add spiderdoctor overlay e2e

.github/workflows/release.yaml, charts/meta-plugins/Chart.yaml, charts/meta-plugins/values.yaml, docs/Release.md
ready to release v0.1.9
Fixes #
=> Update changelog and ready to release v0.1.9

.github/workflows/image-build.yaml, docs/Design.md
=> add design.md doc

.github/workflows/image-build.yaml, .github/workflows/release.yaml, docs/changelog-v0.1.9.md
fix auto release by workflow_dispatch
=> fix auto release by workflow_dispatch

.github/workflows/release.yaml, pkg/utils/utils.go, plugins/router/router.go
fix pod failed to visit host when host multi-nic
Fixes https://github.com/spidernet-io/cni-plugins/issues/110
=> fix pod failed to visit host when host multi-nic

images/Dockerfile
fix dockerfile wrong arch
Fixes #
=> fix dockerfile wrong arch

test/Makefile.defs, test/e2e/macvlan-overlay-one/macvlan_overlay_one_suite_test.go, test/e2e/macvlan-overlay-one/macvlan_overlay_one_test.go, test/e2e/macvlan-overlay-two/macvlan_overlay_two_suite_test.go, test/e2e/macvlan-overlay-two/macvlan_overlay_two_test.go, test/e2e/macvlan-standalone-one/macvlan_standalone_one_suite_test.go, test/e2e/macvlan-standalone-one/macvlan_standalone_one_test.go, test/e2e/macvlan-standalone-two/macvlan_standalone_two_suite_test.go, test/e2e/macvlan-standalone-two/macvlan_standalone_two_test.go, test/scripts/install/05-spiderdoctor.sh
Signed-off-by: ji.li@daocloud.io
=> update spiderdoctor version 0.3.0

Makefile, plugins/veth/veth_test.go
Signed-off-by: ji.li@daocloud.io
=> fix unit test

test/scripts/install/02-multus-underlay.sh, test/scripts/install/03-spiderpool.sh
using ghcr.io when run github e2e
Fixes https://github.com/spidernet-io/cni-plugins/issues/130
=> using ghcr.io when run github e2e

pkg/utils/utils_test.go, plugins/router/router_test.go, plugins/veth/veth_test.go
Signed-off-by: ji.li@daocloud.io
=> add unit-test

.github/workflows/release.yaml, test/scripts/install/01-default-cni.sh, test/scripts/install/03-spiderpool.sh
Fixes https://github.com/spidernet-io/cni-plugins/issues/137
=> fix ci: sleep for pod ready

pkg/utils/utils.go
Signed-off-by: ji.li@daocloud.io
=> fix: overlay route miss net1 route

.github/workflows/ci-bot.yaml, .gitignore, pkg/utils/utils.go, test/scripts/network-config.sh
- enable ipv6 forwarding: to fix ipv6 ci failed
-  revert last changes
Fixes #
=> enable ipv6 forwarding && revert last changes

.github/workflows/release.yaml, test/scripts/install/02-multus-underlay.sh
Fixes https://github.com/spidernet-io/cni-plugins/issues/164
=> e2e ci: ensure crds installed first for multus-underlay

.github/workflows/bin-build.yaml, .github/workflows/e2e-init.yaml, .github/workflows/lint-golang.yaml, go.mod
bump golang version to 1.20
Fixes #
=> bump golang version to 1.20

.github/workflows/release.yaml
=> fix action typo

plugins/router/router.go, plugins/veth/veth.go
cmdDel: ignore pod'ns has gone
Fixes #
=> cmdDel: ignore pod'ns has gone

.github/workflows/image-build.yaml
=> CI: update docker-buildx version

charts/meta-plugins/Chart.yaml, charts/meta-plugins/README.md
=> bump chart to v0.2.7
